"""Alembic environment — reads the Databricks connection from project settings.

There is no offline mode: Databricks DDL is generated by the dialect and the
autogenerate comparison needs a live connection to the warehouse.
"""

from __future__ import annotations

from alembic import context

import core  # noqa: F401 - install the beartype hook first

from config.database import get_metadata
from core.db import get_engine

config = context.config

target_metadata = get_metadata()


def run_migrations_online() -> None:
    with get_engine().connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            # Delta has no ALTER COLUMN TYPE; keep autogenerate from emitting it.
            compare_type=False,
            compare_server_default=False,
        )
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    raise SystemExit(
        "Offline migrations are not supported — Databricks autogenerate "
        "requires a live warehouse connection."
    )

run_migrations_online()
